### ISSUE TITLE
det H ~ 0

### ISSUE THREAD

**Issue by ebonfalke** [printablealice/a4#5]
I have an issue with question 8.
I tried multiple different objectives including the one from Q4 with and without the soft constraints but when I click on optimize in the app the value of O won't change at all (I get only: Warning: det H ~ 0 in the console which I also got for Q4 but there it worked regardless).
Do I have to do something with O to get it minimized or am I missing something?

**Comment by printablealice** [comment]
Thanks for the question!

The warning is telling you that your Hessian matrix is singular (cannot be inverted).  Recall that Newton's method is just a fancy way of saying "your search direction is `H^{-1} * g`".  So if `det H = 0` then officially speaking you can't use Newton.  Eigen is still giving you _something_, but it's apparently hot garbage.

Note that it is very easy to get a singular Hessian.  For example, if one of your optimization variables _just isn't used_, then the corresponding row and column of the Hessian will be zero (since the Hessian is just partial derivatives of your objective).  In your case, `u_K` just isn't used (it shows up nowhere in your objective).

The typical cure to this problem (which doesn't always work, but will in your case) is given as one of the hints to Q8.  Let me know if this doesn't make sense, but I would like to avoid just telling you what to do on this one.

-Jim

**Comment by ebonfalke** [comment]
Thanks, I was able to solve it by changing the weights of the different objectives.
